/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WebAPIForExam
 * OpenAPI spec version: 1.0
 */

export type GetWebapiRequestGetVehicleUsersParams = {
  SearchTerm: string;
  UserToken: string;
};
