/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WebAPIForExam
 * OpenAPI spec version: 1.0
 */

export interface WebAPIRequestSendRequestRequest {
  destination: string;
  source: string;
  userToken: string;
  vehicleUserTypeId: number;
}
